# spring.application.name=api-gateway

# server.port=8080

# # Config Server
# spring.config.import=optional:configserver:http://localhost:8888

# # Eureka Client
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# eureka.client.register-with-eureka=true
# eureka.client.fetch-registry=true

# # Gateway - Service Discovery
# spring.cloud.gateway.discovery.locator.enabled=true
# spring.cloud.gateway.discovery.locator.lower-case-service-id=true


# # ==============================
# # API Gateway Routes
# # ==============================

# # User Service
# spring.cloud.gateway.routes[0].id=user-service
# spring.cloud.gateway.routes[0].uri=lb://user-service
# spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# # Request Service
# spring.cloud.gateway.routes[1].id=request-service
# spring.cloud.gateway.routes[1].uri=lb://request-service
# spring.cloud.gateway.routes[1].predicates[0]=Path=/api/requests/**

# # Provider Service
# spring.cloud.gateway.routes[2].id=provider-service
# spring.cloud.gateway.routes[2].uri=lb://provider-service
# spring.cloud.gateway.routes[2].predicates[0]=Path=/api/providers/**

spring.application.name=api-gateway
server.port=8080

# Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ==============================
# API Gateway Routes (WebMVC gateway)
# ==============================

# User Service
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/users/**

# Request Service
spring.cloud.gateway.server.webmvc.routes[1].id=request-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://request-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/requests/**

# Provider Service
spring.cloud.gateway.server.webmvc.routes[2].id=provider-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://provider-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/providers/**